# variable precedence
# cli level
# task level
# role level
# play level
# inventory level

- name: Variable demo
  hosts: localhost
  connection: local
  vars:
    a: 100
  roles:
    - sample
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: a - {{ a }}
    - name: Print Variable - task level
      vars:
        a: 200
      ansible.builtin.debug:
        msg: a - {{ a }}

- name: Variable demo1
  hosts: all
  tasks:
    - name: Variable from Inventory
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Variable demo2
  hosts: all
  tasks:
    - name: Variable from Inventory vars
      ansible.builtin.debug:
        msg: URL1 - {{ URL1 }}



