- name: Variable demo
  hosts: localhost
  connection: local
  vars:
    a: 100
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: a - {{ a }}
    - name: Print Variable - task level
      vars:
        a: 200
      ansible.builtin.debug:
        msg: a - {{ a }}
