# variable precedence
# cli level
# task level
# role level
# play level
# hosts_vars level
# inventory level
# group_vars level

- name: Variable demo
  hosts: localhost
  connection: local
  vars:
    a: 100
  roles:
    - sample
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: a - {{ a }}
    - name: Print Variable - task level
      vars:
        a: 200
      ansible.builtin.debug:
        msg: a - {{ a }}

- name: Variable demo1
  hosts: all
  tasks:
    - name: Variable from Inventory
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Variable demo2
  hosts: all
  tasks:
    - name: Variable from Inventory vars
      ansible.builtin.debug:
        msg: URL1 - {{ URL1 }}


- name: Facts demo1
  hosts: all
  tasks:
    - name: Print a fact
      ansible.builtin.debug:
        msg: ansible_architecture - {{ ansible_architecture }}

- name: Register results
  hosts: localhost
  connection: local
  tasks:
    - name: Get uptime
      ansible.builtin.shell: uptime
      register: out

    - name:  Print out
      ansible.builtin.debug:
        msg: "{{ out }}"




