- name: Error Handling
  hosts: localhost
  connection: local
  tasks:
    - name: Run a shell command
      ansible.builtin.shell: grep admin /etc/passwd
      register: otu

    - name: print
      ansible.builtin.debug:
        msg: "{{ out.stdout }}"


