- name: Template Demo
  hosts: localhost
  connection: local
  vars:
    name: John
  tasks:
    - name: Copy a file
      ansible.builtin.copy:
        src: sample.txt
        dest: /tmp/sample.txt

